//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tayf.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Link {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Link() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tayf.App_GlobalResources.Link", typeof(Link).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Admin.
        /// </summary>
        public static string addAdmin {
            get {
                return ResourceManager.GetString("addAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Article.
        /// </summary>
        public static string addArticle {
            get {
                return ResourceManager.GetString("addArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Article Category.
        /// </summary>
        public static string addArticleCategory {
            get {
                return ResourceManager.GetString("addArticleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string addcategory {
            get {
                return ResourceManager.GetString("addcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add City.
        /// </summary>
        public static string addCity {
            get {
                return ResourceManager.GetString("addCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Classes.
        /// </summary>
        public static string addClasses {
            get {
                return ResourceManager.GetString("addClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add College.
        /// </summary>
        public static string addCollege {
            get {
                return ResourceManager.GetString("addCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Country.
        /// </summary>
        public static string addCountry {
            get {
                return ResourceManager.GetString("addCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Course.
        /// </summary>
        public static string addCourse {
            get {
                return ResourceManager.GetString("addCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Course Category.
        /// </summary>
        public static string addCourseCategory {
            get {
                return ResourceManager.GetString("addCourseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Criteria.
        /// </summary>
        public static string addCriteria {
            get {
                return ResourceManager.GetString("addCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Degree.
        /// </summary>
        public static string addDegree {
            get {
                return ResourceManager.GetString("addDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Main Menu.
        /// </summary>
        public static string addMainMenu {
            get {
                return ResourceManager.GetString("addMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Manufacturers.
        /// </summary>
        public static string addManufacturers {
            get {
                return ResourceManager.GetString("addManufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add News.
        /// </summary>
        public static string addnews {
            get {
                return ResourceManager.GetString("addnews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Nickname.
        /// </summary>
        public static string AddNickNames {
            get {
                return ResourceManager.GetString("AddNickNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Option.
        /// </summary>
        public static string AddOptions {
            get {
                return ResourceManager.GetString("AddOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add Property.
        /// </summary>
        public static string addProperty {
            get {
                return ResourceManager.GetString("addProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        public static string addQuestion {
            get {
                return ResourceManager.GetString("addQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Scholarship.
        /// </summary>
        public static string addScholarship {
            get {
                return ResourceManager.GetString("addScholarship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Services.
        /// </summary>
        public static string addServices {
            get {
                return ResourceManager.GetString("addServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Slider.
        /// </summary>
        public static string addSlider {
            get {
                return ResourceManager.GetString("addSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Specialization.
        /// </summary>
        public static string addSpecialization {
            get {
                return ResourceManager.GetString("addSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sport.
        /// </summary>
        public static string addSport {
            get {
                return ResourceManager.GetString("addSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trainer.
        /// </summary>
        public static string addTrainer {
            get {
                return ResourceManager.GetString("addTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add University.
        /// </summary>
        public static string addUniversity {
            get {
                return ResourceManager.GetString("addUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Properties.
        /// </summary>
        public static string AdminProperty {
            get {
                return ResourceManager.GetString("AdminProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Category.
        /// </summary>
        public static string ArticleCategory {
            get {
                return ResourceManager.GetString("ArticleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colleges.
        /// </summary>
        public static string Colleges {
            get {
                return ResourceManager.GetString("Colleges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string contactUs {
            get {
                return ResourceManager.GetString("contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contril Panel.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Category.
        /// </summary>
        public static string CourseCategory {
            get {
                return ResourceManager.GetString("CourseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COURSE FEATURES.
        /// </summary>
        public static string courseFeature {
            get {
                return ResourceManager.GetString("courseFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string Criteria {
            get {
                return ResourceManager.GetString("Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria Title.
        /// </summary>
        public static string CriteriaTitle {
            get {
                return ResourceManager.GetString("CriteriaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Queries.
        /// </summary>
        public static string CustomrQueries {
            get {
                return ResourceManager.GetString("CustomrQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Services.
        /// </summary>
        public static string CustomrServices {
            get {
                return ResourceManager.GetString("CustomrServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees.
        /// </summary>
        public static string Degrees {
            get {
                return ResourceManager.GetString("Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Admin.
        /// </summary>
        public static string editAdmin {
            get {
                return ResourceManager.GetString("editAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Article Category.
        /// </summary>
        public static string editAritcleCategory {
            get {
                return ResourceManager.GetString("editAritcleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Article.
        /// </summary>
        public static string editArticle {
            get {
                return ResourceManager.GetString("editArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Article Category.
        /// </summary>
        public static string editArticleCategory {
            get {
                return ResourceManager.GetString("editArticleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string editCategory {
            get {
                return ResourceManager.GetString("editCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit City.
        /// </summary>
        public static string editCity {
            get {
                return ResourceManager.GetString("editCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Classes.
        /// </summary>
        public static string editClasses {
            get {
                return ResourceManager.GetString("editClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit College.
        /// </summary>
        public static string editCollege {
            get {
                return ResourceManager.GetString("editCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Country.
        /// </summary>
        public static string editCountry {
            get {
                return ResourceManager.GetString("editCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Course.
        /// </summary>
        public static string editCourse {
            get {
                return ResourceManager.GetString("editCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Course Category.
        /// </summary>
        public static string editCourseCategory {
            get {
                return ResourceManager.GetString("editCourseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Criteria.
        /// </summary>
        public static string editCriteria {
            get {
                return ResourceManager.GetString("editCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Main Menu.
        /// </summary>
        public static string editMainMenu {
            get {
                return ResourceManager.GetString("editMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Manufacturers.
        /// </summary>
        public static string editManufacturers {
            get {
                return ResourceManager.GetString("editManufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit News.
        /// </summary>
        public static string editnews {
            get {
                return ResourceManager.GetString("editnews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Nickname.
        /// </summary>
        public static string editNickNames {
            get {
                return ResourceManager.GetString("editNickNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Property.
        /// </summary>
        public static string editProperty {
            get {
                return ResourceManager.GetString("editProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Question.
        /// </summary>
        public static string editQuestion {
            get {
                return ResourceManager.GetString("editQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Services.
        /// </summary>
        public static string editServices {
            get {
                return ResourceManager.GetString("editServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Setting.
        /// </summary>
        public static string EditSetting {
            get {
                return ResourceManager.GetString("EditSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Slider.
        /// </summary>
        public static string editSlider {
            get {
                return ResourceManager.GetString("editSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sport.
        /// </summary>
        public static string editSport {
            get {
                return ResourceManager.GetString("editSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Constant.
        /// </summary>
        public static string editStaticList {
            get {
                return ResourceManager.GetString("editStaticList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trainer.
        /// </summary>
        public static string editTrainer {
            get {
                return ResourceManager.GetString("editTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqarati - Statistics.
        /// </summary>
        public static string maintit {
            get {
                return ResourceManager.GetString("maintit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturers.
        /// </summary>
        public static string manufacure {
            get {
                return ResourceManager.GetString("manufacure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send  NewsLetter.
        /// </summary>
        public static string NewsLetter {
            get {
                return ResourceManager.GetString("NewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicknames.
        /// </summary>
        public static string NickNames {
            get {
                return ResourceManager.GetString("NickNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Types.
        /// </summary>
        public static string PropertyTypes {
            get {
                return ResourceManager.GetString("PropertyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Property Type.
        /// </summary>
        public static string PropertyTypesAdd {
            get {
                return ResourceManager.GetString("PropertyTypesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Property Type.
        /// </summary>
        public static string PropertyTypesEdit {
            get {
                return ResourceManager.GetString("PropertyTypesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Text.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Title.
        /// </summary>
        public static string QuestionTitle {
            get {
                return ResourceManager.GetString("QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Cities.
        /// </summary>
        public static string Regions1 {
            get {
                return ResourceManager.GetString("Regions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions Sections.
        /// </summary>
        public static string Regions2 {
            get {
                return ResourceManager.GetString("Regions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Zone.
        /// </summary>
        public static string RegionsAdd {
            get {
                return ResourceManager.GetString("RegionsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Zone.
        /// </summary>
        public static string RegionsEdit {
            get {
                return ResourceManager.GetString("RegionsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply.
        /// </summary>
        public static string replies {
            get {
                return ResourceManager.GetString("replies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Continue.
        /// </summary>
        public static string SaveContinue {
            get {
                return ResourceManager.GetString("SaveContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholarships.
        /// </summary>
        public static string Scholarships {
            get {
                return ResourceManager.GetString("Scholarships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Letter.
        /// </summary>
        public static string SendLetter {
            get {
                return ResourceManager.GetString("SendLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Types.
        /// </summary>
        public static string ServiceTypes {
            get {
                return ResourceManager.GetString("ServiceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service Type.
        /// </summary>
        public static string ServiceTypesAdd {
            get {
                return ResourceManager.GetString("ServiceTypesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service Type.
        /// </summary>
        public static string ServiceTypesEdit {
            get {
                return ResourceManager.GetString("ServiceTypesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share this story, choose your platform.
        /// </summary>
        public static string share {
            get {
                return ResourceManager.GetString("share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliders.
        /// </summary>
        public static string slider {
            get {
                return ResourceManager.GetString("slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specializations.
        /// </summary>
        public static string Specializations {
            get {
                return ResourceManager.GetString("Specializations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        public static string Sports {
            get {
                return ResourceManager.GetString("Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants.
        /// </summary>
        public static string StaticList {
            get {
                return ResourceManager.GetString("StaticList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainee.
        /// </summary>
        public static string Trainee {
            get {
                return ResourceManager.GetString("Trainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer.
        /// </summary>
        public static string Trainer {
            get {
                return ResourceManager.GetString("Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universities.
        /// </summary>
        public static string University {
            get {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Article.
        /// </summary>
        public static string ViewArticle {
            get {
                return ResourceManager.GetString("ViewArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Article Category.
        /// </summary>
        public static string ViewArticleCategory {
            get {
                return ResourceManager.GetString("ViewArticleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Classes.
        /// </summary>
        public static string ViewClasses {
            get {
                return ResourceManager.GetString("ViewClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Countries.
        /// </summary>
        public static string ViewCountry {
            get {
                return ResourceManager.GetString("ViewCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Course.
        /// </summary>
        public static string ViewCourse {
            get {
                return ResourceManager.GetString("ViewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Course Category.
        /// </summary>
        public static string ViewCourseCategory {
            get {
                return ResourceManager.GetString("ViewCourseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Main Menu.
        /// </summary>
        public static string ViewMainMenu {
            get {
                return ResourceManager.GetString("ViewMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Services.
        /// </summary>
        public static string ViewServices {
            get {
                return ResourceManager.GetString("ViewServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Sliders.
        /// </summary>
        public static string ViewSlider {
            get {
                return ResourceManager.GetString("ViewSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Subscriber.
        /// </summary>
        public static string ViewSubscriber {
            get {
                return ResourceManager.GetString("ViewSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Trainer.
        /// </summary>
        public static string ViewTrainer {
            get {
                return ResourceManager.GetString("ViewTrainer", resourceCulture);
            }
        }
    }
}
